- ChangeLog
- README.md
- package.json
#1
- Added git templates in .github directory
- Fixed package name in ChangeLog
- Fixed link string for chmpx document
> Updated files for release 1.0.7

- ChangeLog
- package.json
#4 #5 
- Fixed misspelling, and etc - #5
- Reflected the spelling check result for all sources - #4
> Updated files for release 1.0.8

- README.md
n/a
- Added chmpx nodejs addon overview image to README.md
> Added chmpx nodejs addon overview image to README.md

- ChangeLog
- package.json
n/a
- Added chmpx nodejs addon overview image to README.md - #8
> Updated files for release 1.0.9

- ChangeLog
- package.json
n/a
- Updated version of dependency package(chmpx)
> Updated files for release 1.0.10

- binding.gyp
- package.json
- src/chmpx.cc
- src/chmpx_node.cc
n/a
New support for Node.js 12/14.
As a result, the source code is ready to be built with Node.js 8/10/12/14.
> Supported Node.js 12 and 14

- ChangeLog
- package.json
n/a
- Switched Travis CI to Github actions - #13
- Supported Node.js 12 and 14 - #12
> Updated files for release 1.0.11

- package.json
n/a
Removed install in scripts part of package.json.
> Removed install entry from scripts in package.json file

- tests/run_process_helper.sh
n/a
In the description of `run_process_helper.sh`, the complicated code including the part that uses the which command has been changed to be simple.
> Changed run_process_helper.sh simply instead of the which command etc

- .github/workflows/ci.yml
- .github/workflows/nodejs_helper.sh
- .github/workflows/nodejstypevars.sh
- package.json
- src/chmpx_node_async.h
- tests/run_process_helper.sh
- tests/test.sh
n/a
Overhauled `Github Actions` processes and updated related files.
- Changed support NodeJS to 14/16/18
- Added `npm audit`
- Added `CppCheck`
- Added `ShellCheck`
- Removed `publish-please` and changed to release with `npm publish`
- Change source code(reported from `CppCheck`/`ShellCheck`) due to these changes
> Updated github actions and nodejs version, and fixed bugs

- .github/workflows/ci.yml
- .github/workflows/nodejstypevars.sh
- .gitignore
- .npmignore
- README.md
- index.js
- src/chmpx.cc
- src/chmpx_cbs.cc
- src/chmpx_cbs.h
- src/chmpx_common.h
- src/chmpx_node.cc
- src/chmpx_node.h
- src/chmpx_node_async.h
- tests/chmpx_server.ini
- tests/chmpx_slave.ini
- tests/run_process_helper.sh
- tests/run_process_test_server.js
- tests/run_process_test_slave.js
- tests/test.sh
- tests/unit_all_spec.js
- tests/unit_chmpx_server.js
- tests/unit_chmpx_server_spec.js
- tests/unit_chmpx_slave.js
- tests/unit_chmpx_slave_spec.js
- tests/unit_common.js
- tests/unit_run_process.js
n/a
Reviewed source code header and footer comments.
> Updated header and footer in comment lines

- ChangeLog
- package.json
n/a
- Added build flags and removed unnecessary files - #30
- Updated header and footer in comment lines - #29
- Updated issue/pullrequest templates and README.md - #27
- Reviewed ShellCheck processing again - #26
- Reviewed ShellCheck processing and fixed bugs - #25
- Eliminated unnecessary copies in nodejs_helper.sh - #24
- Updated packages - #23
- Updated github actions and nodejs version, and fixed bugs - #22
- Changed run_process_helper.sh simply instead of the which command etc - #21
- Renamed the test directory to tests and run_test.sh to test.sh - #20
- Removed install entry from scripts in package.json file - #19
- Cleaned up package.json and updated related package versions - #18
> Updated files for release 1.0.13

- package.json
#19
I accidentally deleted the install command in package.json, so I restored it.
> Fixed package.json for install command

- ChangeLog
- package.json
n/a
- Fixed package.json for install command - #32
> Updated files for release 1.0.14

- .github/workflows/nodejs_helper.sh
n/a
Updated the build helper scripts.
> Updated building/packaging scripts

- ChangeLog
- package.json
n/a
- Updated building/packaging scripts - #34
> Updated files for release 1.0.15

- ChangeLog
- package.json
n/a
- Updated support NodeJS version - #37
> Updated files for release 1.0.16

- ChangeLog
- package.json
n/a
- Updated versions of dependent packages - #39
> Updated files for release 1.0.17

- .github/workflows/ci.yml
- package.json
- src/chmpx_cbs.cc
n/a
- Updated dependency package versions.
- Changed the OS of the `Github Actions` to `ubuntu-latest`.
- Fixed errors about `cppcheck`.
- Changed the local build environment. (Change `Frdora37` to `Fedora38`)
> Changed CI Runner OS and updated dependencies

- ChangeLog
- package.json
n/a
- Changed CI Runner OS and updated dependencies - #41
> Updated files for release 1.0.18

- .auditignore
n/a
The `.auditignore` file has been deleted as it is no longer needed.
> Removed .auditignore file

- ChangeLog
- package.json
n/a
- Updated github actions tools and dependencies - #45
> Updated files for release 1.0.20

- ChangeLog
- package.json
n/a
- Changed supported OS and NodeJS version - #47
> Updated files for release 1.0.21

- ChangeLog
- package.json
n/a
- Changed publish NodeJS versions to v22 and Fixed scripts, etc - #49
> Updated files for release 1.0.22

- ChangeLog
- package.json
n/a
- Updated a dependent package version(mocha) - #51
> Updated files for release 1.0.23
